#ifndef SORTINGBYSHELLLIBRARY_GLOBAL_H
#define SORTINGBYSHELLLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QList>

#if defined(SORTINGBYSHELLLIBRARY_LIBRARY)
#define SORTINGBYSHELLLIBRARY_EXPORT Q_DECL_EXPORT
#else
#define SORTINGBYSHELLLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // SORTINGBYSHELLLIBRARY_GLOBAL_H
